### PR TITLE
Ms/dev 2.0

### PR DESCRIPTION
**Pull request by mstefferson**
Changes:

* Added 2.0
* 2.0 used python3.7 and ubuntu 18.04
* Removed git (unused)
* Don't copy Dockerfile (doesn't do anything)
* Base image has `wheel` and `setuptools`. These are core packages and should be here.

Note:
Figuring out the change `python3-dev` -> `python3.7-dev` almost broke me

### CODE REVIEW

**Comment by rkoppula** [comment]
There were couple of instances where we needed to install a package from it's source by first doing a git clone and then run pip install or make. That's the reason to have git. What is this comment about not copying Dockerfile? Can you point me to the change that corresponds to this comment?

**Comment by mstefferson** [comment]
Added back `git`

**Comment by mstefferson** [comment]
Removed `COPY . /build`

**Comment by rkoppula** [comment]
@mstefferson You added back git? I don't see it in Dockerfiles.

**Pull request merged**
